### ISSUE TITLE
Tries to use window.XDomainRequest when in zombie.js

### ISSUE THREAD

**Issue by mmmmmrob** [mapbox/mapbox.js#1152]
Hi, not sure if this is a mapbox issue or a zombie issue, so happy to be told to repost elsewhere.

When running within zombie.js for fast integration tests of may web app mapbox.js fails with a call to the IE-specific function window.XDomainRequest.

`Unhandled rejection Error: window.XDomainRequest is not a function
    at corslite (http://example.com/bower_components/mapbox.js/mapbox.js:2:462)
    at module.exports (http://example.com/bower_components/mapbox.js/mapbox.js:55:508)
    at module.exports._loadTileJSON (http://example.com/bower_components/mapbox.js/mapbox.js:45:231)
    at L.Map.extend.initialize (http://example.com/bower_components/mapbox.js/mapbox.js:47:2529)
    at new e (http://example.com/bower_components/mapbox.js/mapbox.js:6:2539)
    at Object.module.exports.map (http://example.com/bower_components/mapbox.js/mapbox.js:47:4939)
    at http://example.com/javascripts/map.js:4:22
    at Object.exports.runInContext (vm.js:44:17)
    at window._evaluate (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/document.js:253:75)
    at Object.DOM.languageProcessors.javascript (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/dom/scripts.js:26:12)
From previous event:
    at Browser.wait (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/index.js:341:145)
    at lazyResolve (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/index.js:390:40)
    at Object.then (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/index.js:397:18)
    at Context.<anonymous> (/Users/rs/WebstormProjects/example/test/book_a_valuation.zombie.js:31:8)
    at callFnAsync (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:349:8)
    at Test.Runnable.run (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:301:7)
    at Runner.runTest (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:422:10)
    at /Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:528:12
    at next (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:342:14)
    at /Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:352:7
    at next (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:284:14)
    at /Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:315:7
    at done (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:287:5)
    at /Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:331:11
    at EventLoop.done (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/eventloop.js:589:11)
    at EventLoop.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at EventLoop.emit (events.js:179:7)
    at Immediate._onImmediate (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/eventloop.js:688:71)
From previous event:
    at Object.then (/Users/rs/WebstormProjects/example/node_modules/zombie/lib/index.js:397:32)
    at callFn (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:330:10)
    at Hook.Runnable.run (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runnable.js:319:7)
    at next (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:298:10)
    at Immediate._onImmediate (/Users/rs/WebstormProjects/example/node_modules/mocha/lib/runner.js:320:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by jfirebaugh** [comment]
It's almost certainly a bug in zombie.js or another library that improperly implements a shim for XMLHttpRequest. See similar issues like https://github.com/mapbox/corslite/issues/14 and https://github.com/mapbox/corslite/issues/13.
