### ISSUE TITLE
Cannot build with webpack

### ISSUE THREAD

**Issue by minessis** [mapbox/mapbox.js#1172]
Recreating issue:
From project folder
`npm i --save mapbox.js`
`vi ./index.js`
Add the following line to index.js
`require('mapbox.js');`
Build with webpack gets following output:

``` bash
ERROR in ./~/mapbox.js/package.json
Module parse failed: /proj/node_modules/mapbox.js/package.json Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:10)
    at Parser.pp$4.raise (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/proj/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/proj/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/proj/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/proj/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/proj/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/proj/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/proj/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/proj/node_modules/webpack/lib/Compilation.js:126:9)
    at /proj/node_modules/webpack/lib/Compilation.js:309:10
    at /proj/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/proj/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/proj/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/proj/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /proj/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /proj/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /proj/node_modules/webpack/node_modules/async/lib/async.js:52:16
 @ ./~/mapbox.js/src/mapbox.js 54:4-30
```

In both cases, line 2 and line 54 of mapbox.js are doing the following:

``` javascript
require('../package.json').version 
```

But, if I do the following:
`cd ./node_modules/mapbox.js`
`node`
`> var p = require('./package.json');`
`> console.log(p.version);`
The package version is output without error:
`'2.4.0'`

This is all very strange as the package.json is valid json.

Please advise!

**Comment by minessis** [comment]
This was a json-loader error...
Resolved with the following addition to webpack.config.js loaders array

``` javascript
{ test: /\.json$/, loader: "json-loader" }
```
